### ISSUE TITLE
go wrong

### ISSUE THREAD

**Issue by SUNJIE-FOXMAIL** [VoChiDanh/SoulPoints#3]
[23:38:15] [Server thread/ERROR]: Error occurred while enabling SoulPoints v1.2.9.2 (Is it up to date?)
java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/mobs/entities/MythicEntity
        at net.danh.diemsinhmenh.Main.onEnable(Main.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:520) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:434) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.mobs.entities.MythicEntity
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 11 more

**Comment by VoChiDanh** [comment]
- 4119e15: fix issues mythicmobs
Thanks for reporting
