### ISSUE TITLE
WARN

### ISSUE THREAD

**Issue by SUNJIE-FOXMAIL** [VoChiDanh/SoulPoints#4]
[SoulPoints] Task #53 for SoulPoints v1.2.9.3 generated an exception
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because "s" is null
        at net.danh.diemsinhmenh.Main.convert(Main.java:214) ~[?:?]
        at net.danh.diemsinhmenh.Main$2.run(Main.java:115) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by VoChiDanh** [comment]
How do you get this error?... Is it when joining the game?

**Comment by VoChiDanh** [comment]
I'm not sure about this but maybe the plugin was trying to make the actionbar to send the player in the world hasn't finished loading yet hmm

**Comment by VoChiDanh** [comment]
ah wait

**Comment by VoChiDanh** [comment]
Can you try this? https://github.com/VoChiDanh/SoulPoints/releases/download/v1.2.9/SoulPoints.jar

**Comment by SUNJIE-FOXMAIL** [comment]
[SoulPoints] Task #46 for SoulPoints v1.2.9.4 generated an exception
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null
        at net.danh.diemsinhmenh.Main$2.run(Main.java:113) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by VoChiDanh** [comment]
can you try again~~?

**Comment by SUNJIE-FOXMAIL** [comment]
perfect

**Comment by VoChiDanh** [comment]
I think the error is when it tries to create the action bar when the world hasn't loaded yet ~~

**Comment by VoChiDanh** [comment]
close it if you have resolved the error ~~, ty for reporting

**Comment by SUNJIE-FOXMAIL** [comment]
[15:52:52] [Server thread/WARN]: [SoulPoints] Task #46 for SoulPoints v1.2.9.3 generated an exception
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because "s" is null
        at net.danh.diemsinhmenh.Main.convert(Main.java:214) ~[?:?]
        at net.danh.diemsinhmenh.Main$2.run(Main.java:115) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at java.lang.Thread.run(Thread.java:833) [?:?]
>

Automatic points increment 
error

**Comment by VoChiDanh** [comment]
try 1.2.9.4 devbuild, i'll upload 1.2.9.4 to spigotmc

**Comment by SUNJIE-FOXMAIL** [comment]
[SoulPoints] Task #46 for SoulPoints v1.2.9.4 generated an exception
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null
        at net.danh.diemsinhmenh.Main$2.run(Main.java:113) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at java.lang.Thread.run(Thread.java:833) [?:?]
>
Wrong: Still adds points for no reason

**Comment by VoChiDanh** [comment]
okok, wait

**Comment by VoChiDanh** [comment]
okee, can you try devbuild again? Really sorry about these problems :(

**Comment by SUNJIE-FOXMAIL** [comment]
[SoulPoints] Task #46 for SoulPoints v1.2.9.4 generated an exception
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null
        at net.danh.diemsinhmenh.Main$2.run(Main.java:113) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at java.lang.Thread.run(Thread.java:833) [?:?]
>
Wrong: Still adds points for no reason

**Comment by SUNJIE-FOXMAIL** [comment]
[16:15:02] [Server thread/INFO]: Goya issued server command: /souls set Goya 0
[16:15:55] [Server thread/WARN]: [SoulPoints] Task #46 for SoulPoints v1.2.9.4 generated an exception
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null
        at net.danh.diemsinhmenh.Main$2.run(Main.java:118) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[16:16:55] [Server thread/WARN]: [SoulPoints] Task #46 for SoulPoints v1.2.9.4 generated an exception
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null
        at net.danh.diemsinhmenh.Main$2.run(Main.java:118) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[16:16:55] [Server thread/INFO]: [EliteMobs] Event coins_goblin.yml has been queued!
[16:17:55] [Server thread/WARN]: [SoulPoints] Task #46 for SoulPoints v1.2.9.4 generated an exception
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null
        at net.danh.diemsinhmenh.Main$2.run(Main.java:118) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by VoChiDanh** [comment]
ah commands

**Comment by VoChiDanh** [comment]
hmmm, wait ~~

**Comment by VoChiDanh** [comment]
Have you added "souls.use" permission? Also have you added that world to your config?

**Comment by SUNJIE-FOXMAIL** [comment]
Goya was shot by Skeleton
[16:26:21] [Server thread/WARN]: [SoulPoints] Task #46 for SoulPoints v1.2.9.4 generated an exception
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null
        at net.danh.diemsinhmenh.Main$2.run(Main.java:118) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot.jar:3276-Spigot-3892929-b58f429]
        at java.lang.Thread.run(Thread.java:833) [?:?]

Confirm to add souls.use 
Items are now brushed after death after adding permissions

**Comment by VoChiDanh** [comment]
can you paste your config.yml to pastebin? and lang.yml too

**Comment by SUNJIE-FOXMAIL** [comment]
config-version: 8
DropRandomItems: true #false to lost all inventory
language: zhCN
available-worlds:
  - world
  - world_nether
  - world_the_end
PVP:
  Enable: true
  Kill-souls: 1
Mobs:
  Enable: true
ActionBar:
  Enable: true
General:
  Maximum-souls: 7
  Death-souls: 1
  Daily-souls: 1
  Souls-regenerate-duration: 60 #60 = 1s
  Respawn_souls: 3
  Lose-soul-message-after: 3
  First_join: 5
  Minimum_souls: 1


lang:
  enUs:
       Soul-earn-message: '&d[Souls] &fYou have earned %souls% Soul!'
       Death-message: '&d[Souls] &fYou lost %lost% souls because you dead, You have %souls% Souls Now!'
       Death-message-inventory: '&4[Souls] &cYou have lost random item because you do not enough souls to keep it!'
       Kill-message: '&d[Souls] &bYou receive %souls% Souls because you killed %player%'
       Reset-message: '&d[Souls] &6You have set the souls of %player% to %souls%'
       Kill-mobs-message: '&d[Souls] &bYou get %souls% souls from killing mobs &f(&e%mob%&f)'
       Take-message: '&4[Souls] &cRemove %souls% souls from %player%'
       Add-message: '&4[Souls] &cAdd %souls% souls to %player%'
       Set-message: '&4[Souls] &cSet %souls% souls to %player%'
       Check-message: '&4[Souls] &c%player% has %souls%'
       Soul-message: '&d[Souls] &fYou have %souls% souls!'
       Not-online: '&d[Souls] &cThat player is not online!'
       Enough: '&d[Souls] &cToo much amount to remove!'
       Reload: '&d[Souls] &cReload Config'
       Perm: '&d[Souls] &cYou can not do this command'
  zhCN:
       Soul-earn-message: '&d[Souls] &f你获得了 %souls% 灵魂点数!'
       Death-message: '&d[Souls] &f你失去了 %lost% 点灵魂点数, 现在有 %souls% 灵魂点数剩余!'
       Death-message-inventory: '&4[Souls] &c缺少足够灵魂点数, 背包内物品已随机掉落!'
       Kill-message: '&d[Souls] &b你通过击杀玩家 %player% 获得了 %souls% 灵魂点数'
       Reset-message: '&d[Souls] &6您已将 %player% 的灵魂设置为 %souls%'
       Kill-mobs-message: '&d[Souls] &b你通过杀死怪物获得 %souls% 的灵魂 &f(&e%mob%&f)'
       Take-message: '&4[Souls] &c你移除了玩家 %player% %souls% 点灵魂点数'
       Add-message: '&4[Souls] &c给予玩家 %player% 了点 %souls%灵魂点数'
       Set-message: '&4[Souls] &c将玩家 %player% 的灵魂点数设置为了 %souls%'
       Check-message: '&4[Souls] &c%player% 拥有 %souls% 点灵魂点数'
       Soul-message: '&d[Souls] &f你现在有 %souls% 灵魂点数!'
       Not-online: '&d[Souls] &c玩家不在线!'
       Enough: '&d[Souls] &c移除的灵魂点数过多!'
       Reload: '&d[Souls] &c配置已重载'
       Perm: '&d[Souls] &c你不能执行这个命令'
  viVN:
    Soul-earn-message: '&d[Souls] &fBạn nhận được %souls% Souls!'
    Death-message: '&d[Souls] &fBạn đã chết và mất %lost% souls, bạn còn %souls% Souls!'
    Death-message-inventory: '&4[Souls] &cBạn đã bị mất đồ vì mất hết souls!'
    Kill-message: '&d[Souls] &bBạn nhận được %souls% Souls vì bạn giết người chơi %player%'
    Reset-message: '&d[Souls] &6Bạn đã đặt số souls của %player% thành %souls%'
    Kill-mobs-message: '&d[Souls] &bBạn nhận được %souls% Souls từ việc giết mobs &f(&e%mob%&f)'
    Take-message: '&4[Souls] &cLoại bỏ %souls% souls từ %player%'
    Add-message: '&4[Souls] &cThêm %souls% souls cho %player%'
    Set-message: '&4[Souls] &cĐặt %souls% souls cho %player%'
    Check-message: '&4[Souls] &c%player% có %souls%'
    Soul-message: '&d[Souls] &fBạn có %souls% souls!'
    Not-online: '&d[Souls] &cNgười chơi không hoạt động!'
    Enough: '&d[Souls] &cKhông đủ để loại bỏ!'
    Reload: '&d[Souls] &cTải lại config'
    Perm: '&d[Souls] &cBạn không thể thực hiện lệnh đó'
Help-player:
  - "&a/souls check <player> &f- &7Check souls of player"
Help-admin:
  - "&a/souls check <player> &f- &7Check souls of player"
  - "&a/souls add <player> <amount> &f- &7Add souls "
  - "&a/souls remove <player> <amount> &f- &7Remove souls"
  - "&a/souls set <player> <amount> &f- &7Set souls"
  - "&a/souls reload &f- &7Reload Config"
lang-version: 2

**Comment by SUNJIE-FOXMAIL** [comment]
All by default

**Comment by VoChiDanh** [comment]
can you try lastest devbuild? I just finished studying and i will try it on my server too

**Comment by VoChiDanh** [comment]
oke, i know why.. wait...

**Comment by VoChiDanh** [comment]
yooooo doneee

**Comment by VoChiDanh** [comment]
remember /gamerule keepinventory true

**Comment by VoChiDanh** [comment]
oke, check new update on spigotmc
