### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by SUNJIE-FOXMAIL** [VoChiDanh/SoulPoints#5]
[SuperVanish] StackTrace:
[19:37:03] [pool-39-thread-6/WARN]: java.lang.RuntimeException: Failed to construct PlayerInfoData.
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.wrappers.PlayerInfoData$1.getGeneric(PlayerInfoData.java:129)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.wrappers.PlayerInfoData$1.getGeneric(PlayerInfoData.java:96)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.wrappers.BukkitConverters.getGenericList(BukkitConverters.java:300)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.wrappers.BukkitConverters.access$100(BukkitConverters.java:88)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:367)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:359)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:48)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
[19:37:03] [pool-39-thread-6/WARN]:     at de.myzelyam.supervanish.features.SilentOpenChestPacketAdapter.onPacketSending(SilentOpenChestPacketAdapter.java:73)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[19:37:03] [pool-39-thread-6/WARN]:     at net.minecraft.network.NetworkManager.b(NetworkManager.java:203)
[19:37:03] [pool-39-thread-6/WARN]:     at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:183)
[19:37:03] [pool-39-thread-6/WARN]:     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1695)
[19:37:03] [pool-39-thread-6/WARN]:     at net.minecraft.server.network.PlayerConnection.sendPacket(PlayerConnection.java:1681)
[19:37:03] [pool-39-thread-6/WARN]:     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:37:03] [pool-39-thread-6/WARN]:     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[19:37:03] [pool-39-thread-6/WARN]:     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:37:03] [pool-39-thread-6/WARN]:     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[19:37:03] [pool-39-thread-6/WARN]:     at me.neznamy.tab.platforms.bukkit.BukkitTabPlayer.sendPacket(BukkitTabPlayer.java:101)
[19:37:03] [pool-39-thread-6/WARN]:     at me.neznamy.tab.shared.ITabPlayer.sendCustomPacket(ITabPlayer.java:233)
[19:37:03] [pool-39-thread-6/WARN]:     at me.neznamy.tab.shared.ITabPlayer.sendCustomPacket(ITabPlayer.java:239)
[19:37:03] [pool-39-thread-6/WARN]:     at me.neznamy.tab.shared.features.Playerlist.refresh(Playerlist.java:163)
[19:37:03] [pool-39-thread-6/WARN]:     at me.neznamy.tab.shared.features.Playerlist.lambda$onJoin$0(Playerlist.java:186)
[19:37:03] [pool-39-thread-6/WARN]:     at me.neznamy.tab.shared.features.Playerlist.onJoin(Playerlist.java:195)
[19:37:03] [pool-39-thread-6/WARN]:     at me.neznamy.tab.shared.FeatureManager.onJoin(FeatureManager.java:211)
[19:37:03] [pool-39-thread-6/WARN]:     at me.neznamy.tab.platforms.bukkit.BukkitEventListener.lambda$onJoin$1(BukkitEventListener.java:46)
[19:37:03] [pool-39-thread-6/WARN]:     at me.neznamy.tab.shared.cpu.CPUManager.lambda$submit$4(CPUManager.java:180)
[19:37:03] [pool-39-thread-6/WARN]:     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[19:37:03] [pool-39-thread-6/WARN]:     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[19:37:03] [pool-39-thread-6/WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:37:03] [pool-39-thread-6/WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:37:03] [pool-39-thread-6/WARN]:     at java.base/java.lang.Thread.run(Thread.java:833)
[19:37:03] [pool-39-thread-6/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Enum.name()" because "specific" is null
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getGeneric(EnumWrappers.java:811)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getGeneric(EnumWrappers.java:792)
[19:37:03] [pool-39-thread-6/WARN]:     at com.comphenix.protocol.wrappers.PlayerInfoData$1.getGeneric(PlayerInfoData.java:120)
[19:37:03] [pool-39-thread-6/WARN]:     ... 43 more

**Comment by VoChiDanh** [comment]
this is not my plugins error, maybe supervanish error (please include full logs if you confirm what is the error caused by my plugins)

**Comment by SUNJIE-FOXMAIL** [comment]
Well, I already know there's a problem

**Comment by SUNJIE-FOXMAIL** [comment]
I'm sorry to have misread it
